spring.application.name=banking-app 
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/banking_app
spring.datasource.username=root
spring.datasource.password=Kant\#12345
spring.jpa.hibernate.ddl-auto=update

